version: 2

jobs:
    build:
        docker:
            - image: node
        steps:
            - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
            - run:
                name: "Verify Rust installation"
                command: rustc --version
            - checkout
            - run: cargo generate-lockfile
            - restore-cache:
                keys:
                    - v1-cargo-cache-{{ checksum "Cargo.lock" }}
            - run: cargo build --all --all-targets
            - save_cache:
                paths:
                    - /usr/local/cargo/registry
                    - target/debug/.fingerprint
                    - target/debug/build
                    - target/debug/deps
                key: v1-cargo-cache-{{ checksum "Cargo.lock" }}
            - run: cargo test --all
